---
title: "acp_variables"
output: html_document
date: "2024-11-15"
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               class.source="badCode")

library(reshape2)
library(ggplot2)
library(FactoMineR)
library(factoextra)
library(corrplot)
```

## R Markdown

Importer les données :

```{r}
data <-read.table("DataProjet4modIA-2425.txt",header=T)
head(data)
```



## R Markdown
notes non formelles :
On voit sur le boxplot que les repliquats on la même "forme'.
Les variables n'on pas le même ordre de grandeur, il faudra normaliser avant de faire l'ACP.


```{r}
data_t = as.data.frame(t(data))
head(data_t)

res_pca = PCA(data_t, scale.unit = T, grap=F)

fviz_pca_ind(res_pca)
rand_var = sample(colnames(data_t),15)
fviz_pca_var(res_pca, select.var = list(name=rand_var, cos2=NULL, contrib=NULL))
fviz_pca_var(res_pca, select.var = list(contrib=5))
```


```{r}
n = length(data$T1_1h_R1)
n
(1/sqrt(n)) * res_pca$eig[1:15,]


```

```{r}
fviz_eig(res_pca)
fviz_contrib(res_pca, choice="ind", axes=1)
fviz_contrib(res_pca, choice="ind", axes=2)
fviz_contrib(res_pca, choice="var", axes = 1, top=20)
fviz_contrib(res_pca, choice="var", axes = 2, top=20)
# geom choix des var
# contrib = -> sueil
# tracer un corrplot de correlation
# repeal = T
# police
```
```{r}
corrplot(t(res_pca$var$cor))
res_pca$var$contribpca
fviz_res_
# qt 1 organisation des var -> ACP des variavbles
```