---
title: "interpretation_acp"
output: pdf_document
date: "2025-01-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reshape2)
library(ggplot2)
library(FactoMineR)
library(factoextra)
library(corrplot)
library(mclust)
library(clusterSim)
library(ggplot2)
library(circlize)
library(viridis)
```


```{r }
data <-read.table("DataProjet4modIA-2425.txt",header=T)
kable(head(data),caption="\\label{tab:data}Les premières lignes du jeu de données du projet")
```


```{r}
mean_replicat <- function(data){
  
  # Moyenne des replicats
  for (j in 1:18){
    data[, j] = (data[, j] + data[, j+18]) / 2
    m = length(colnames(data)[j])
    colnames(data)[j] = substr(colnames(data)[j], 1, nchar(colnames(data)[j]) - 3)
  }
  data = data[, 1:18]
  return(data)
}

data_mean = mean_replicat(data)

get_code = function(variable){
  # 1-> sur
  # 0 -> sous
  # -1 -> non exprimé
  
  code = rep(-1, length(variable))
  
  code[variable < -1] = 0
  code[variable > 1] = 1
  code = as.factor(code)
  return(code)
}

code.T1_6h = get_code(data_mean$T1_6h)
code.T2_6h = get_code(data_mean$T2_6h)
code.T3_6h = get_code(data_mean$T3_6h)

code.T1_1h = get_code(data_mean$T1_1h)
code.T2_1h = get_code(data_mean$T2_1h)
code.T3_1h = get_code(data_mean$T3_1h)

code.T1_3h = get_code(data_mean$T1_3h)
code.T2_3h = get_code(data_mean$T2_3h)
code.T3_3h = get_code(data_mean$T3_3h)


code.T1_6h_R1 = get_code(data$T1_6h_R1)
code.T2_6h_R1 = get_code(data$T1_6h_R1)
code.T3_6h_R1 = get_code(data$T1_6h_R1)

code.T1_6h_R2 = get_code(data$T1_6h_R2)
code.T2_6h_R2 = get_code(data$T1_6h_R2)
code.T3_6h_R2 = get_code(data$T1_6h_R2)
```

ACP des individus : Les variables sont homogènes donc on ne scale pas

```{r}
acp.ind = PCA(data, scale.unit = F, graph = F)
#fviz_eig(acp.ind)
```


```{r}
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T1_6h, axes=c(1, 2))
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T2_6h, axes=c(1, 2))
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T3_6h, axes=c(1, 2))
```

```{r}
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T1_1h, axes=c(1, 2))
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T2_1h, axes=c(1, 2))
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T3_1h, axes=c(1, 2))
```

```{r}
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T1_3h, axes=c(1, 2))
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T2_3h, axes=c(1, 2))
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T3_3h, axes=c(1, 2))
```

```{r}
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T1_6h_R1, axes=c(1, 2))
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T2_6h_R1, axes=c(1, 2))
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T3_6h_R1, axes=c(1, 2))
```

```{r}
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T1_6h_R2, axes=c(1, 2))
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T2_6h_R2, axes=c(1, 2))
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T3_6h_R2, axes=c(1, 2))
```

```{r}
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T1_6h, axes=c(1, 3))
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T2_6h, axes=c(1, 3))
fviz_pca_ind(acp.ind, geom = c("point"), habillage=code.T3_6h, axes=c(1, 3))
```

```{r}
traitements = as.factor(substr(colnames(data), 2, 2))
heures = as.factor(substr(colnames(data), 4, 4))
replicats = as.factor(substr(colnames(data), 8, 8))
```


```{r}
fviz_pca_var(acp.ind, col.var=traitements, axes=c(1, 2), legend.title="Traitement")
fviz_pca_var(acp.ind, col.var=heures, axes=c(1, 2), legend.title="heure")
fviz_pca_var(acp.ind, col.var=replicats, axes=c(1, 2), legend.title="replicats")
```

```{r}
fviz_pca_var(acp.ind, col.var=traitements, axes=c(1, 3), legend.title="Traitement")
fviz_pca_var(acp.ind, col.var=heures, axes=c(1, 3), legend.title="heure")
fviz_pca_var(acp.ind, col.var=replicats, axes=c(1, 3), legend.title="replicats")
```
Notes:
axe 1 et 2 effets des traitements 2 et 3 (petite correlation avec 1):
  Sur l'axe 1 : expression des gènes : sur exprimé versus sous exprimé
  Sur l'axe 2 : effet temporel 
  
axe 3:
  informations de l'axe 1


```{r}
acp.var = PCA(t(data), scale.unit = F, graph = F)
fviz_eig(acp.var)
```



```{r}
fviz_pca_ind(acp.var, habillage=traitements, axes=c(1, 2))
fviz_pca_ind(acp.var, habillage=heures, axes=c(1, 2))
fviz_pca_ind(acp.var, habillage=replicats, axes=c(1, 2))
```

```{r}
fviz_pca_ind(acp.var, habillage=traitements, axes=c(1, 3))
fviz_pca_ind(acp.var, habillage=heures, axes=c(1, 3))
fviz_pca_ind(acp.var, habillage=replicats, axes=c(1, 3))
```


```{r}
fviz_pca_var(acp.var, col.var=code.T1_6h, axes=c(1, 2), legend.title="Traitement", geom="point")
fviz_pca_var(acp.var, col.var=code.T2_6h, axes=c(1, 2), legend.title="Traitement", geom="point")
fviz_pca_var(acp.var, col.var=code.T3_6h, axes=c(1, 2), legend.title="Traitement", geom="point")
```


```{r}
fviz_pca_var(acp.var, col.var=code.T1_6h, axes=c(1, 3), legend.title="Traitement", geom="point")
fviz_pca_var(acp.var, col.var=code.T2_6h, axes=c(1, 3), legend.title="Traitement", geom="point")
fviz_pca_var(acp.var, col.var=code.T3_6h, axes=c(1, 3), legend.title="Traitement", geom="point")
```


